name: Flask Application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install nginx
      run: sudo apt-get install -y nginx
    - name: Start uvicorn
      run: |
        uvicorn app:app --host 0.0.0.0 --port 8000 &
    - name: Configure nginx
      run: |
        sudo rm /etc/nginx/sites-enabled/default
        echo 'server {
          listen 80;
          server_name _;

          location / {
            proxy_pass http://0.0.0.0:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
        }' | sudo tee /etc/nginx/sites-available/default
    - name: Restart nginx
      run: sudo service nginx restart
